# Generated by Kitchn - Do not edit manually
# This file defines the theme variables for the Textual TUI

# Colors
PRIMARY = "#FF79C6"
SECONDARY = "#BD93F9"
ACCENT = "#00ffff"
SURFACE = "#121212"
PANEL = "#1e1e1e"
TEXT = "#ffffff"
ERROR = "#FF5555"

# Styling
CSS_VARIABLES = {
    "primary": PRIMARY,
    "secondary": SECONDARY,
    "accent": ACCENT,
    "surface": SURFACE,
    "panel": PANEL,
    "text": TEXT,
    "error": ERROR
}
