# Generated by Kitchn - Do not edit manually
# This file defines the theme variables for the Textual TUI

# Colors from Kitchn theme
PRIMARY = "#FF79C6"
SECONDARY = "#BD93F9"
ACCENT = "#6AC5D3"
BG = "#161925"
FG = "#F8F8F2"
SURFACE = "#161925"
PANEL = "#11131C"
TEXT = "#F8F8F2"
ERROR = "#FF5555"
SUCCESS = "#50FA7B"
WARNING = "#FFB86C"
INFO = "#8BE9FD"

# Styling
CSS_VARIABLES = {
    "primary": PRIMARY,
    "secondary": SECONDARY,
    "accent": ACCENT,
    "background": BG,
    "foreground": FG,
    "surface": SURFACE,
    "panel": PANEL,
    "text": TEXT,
    "error": ERROR,
    "success": SUCCESS,
    "warning": WARNING,
    "info": INFO,
}
